import type { Metadata } from "next";
import "./globals.css";

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { ListingProvider } from "@/context/ListingContext";
import QueryProvider from "@/context/QueryProvider";
import { InterceptionContext } from "@/context/InterceptionContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <ListingProvider>
            <InterceptionContext>{children}</InterceptionContext>
          </ListingProvider>
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryProvider>
      </body>
    </html>
  );
}
